alias pro='cd ~/Desktop/Programming/'
alias back='cd -'
alias nvimconf='cd ~/.config/nvim/ && nvim'
alias csie1929='cd ~/Desktop/Programming/Python/csie1929/'
alias python='python3'
alias zshconfig='nvim ~/.zshrc'
alias aliasconfig='nvim ~/.oh-my-zsh/custom/aliases.zsh'
alias judgegirl='cd ~/Desktop/Programming/csiejudgegirl/'
